name: Python CI

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows users to manually trigger the workflow from the GitHub Actions tab

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python/lexio

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for hatch-vcs

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]"

    - name: Generate Python Types
      working-directory: ${{ github.workspace }}
      run: |
        cd rag-ui
        npm ci
        npm run generate-types

    - name: Generate Python Package
      working-directory: ${{ github.workspace }}
      run: |
        cd rag-ui
        npm ci
        npm run generate-python-package

    - name: Run Python Tests
      run: pytest tests -v

    - name: Build package
      run: hatch build

    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: python/lexio/dist/
        retention-days: 7

  test:
    needs: build
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    defaults:
      run:
        working-directory: python/lexio

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Download built package
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist

    - name: Install built package
      run: |
        python -m pip install --upgrade pip
        pip install dist/*.whl
        pip install ".[dev]"

    - name: Run tests
      run: pytest tests -v
