name: Release Python Package

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python/lexio

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for setuptools_scm

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Generate Types
      working-directory: ${{ github.workspace }}
      run: |
        cd rag-ui
        npm ci
        npm run generate-types
        cd ../python/lexio

    - name: Run tests
      run: |
        pip install -e ".[dev]"
        pytest tests -v

    - name: Build package
      run: python -m build

    - name: Check package
      run: twine check dist/*

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: python/lexio/dist/*
        generate_release_notes: true 