name: Release Python Package

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows users to manually trigger the workflow from the GitHub Actions tab


jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
#        python-version: ["3.9", "3.10", "3.11", "3.12"]  # Testen auf mehreren Python-Versionen
        python-version: ["3.9", "3.10", "3.11", "3.12"]  # Testen auf mehreren Python-Versionen
    defaults:
      run:
        working-directory: python/lexio

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for setuptools_scm

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Generate Types
      working-directory: ${{ github.workspace }}
      run: |
        cd rag-ui
        npm ci
        npm run generate-types

    - name: Generate Python Package
      working-directory: ${{ github.workspace }}
      run: |
        cd rag-ui
        npm ci
        npm run generate-python-package

    - name: Run Python Tests
      working-directory: ${{ github.workspace }}
      run: |
        cd rag-ui
        npm ci
        npm run test-python-package

    - name: Build package
      run: python -m build

    - name: Upload Build as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lexio-python-${{ matrix.python-version }}
        path: ${{ github.workspace }}/python/lexio/dist/*

    - name: Check package
      run: twine check dist/*

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: twine upload dist/*
