name: Release to NPM

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
    branches:
      - 'feature/testing-concept'  # Add temporary trigger for testing
  workflow_dispatch:  # Allows manual triggering

jobs:
  checks:
    uses: ./.github/workflows/check.yml  # Reuse the check workflow (for lint/test/typecheck only)

  publish:
    needs: checks  # Wait for checks to pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: './rag-ui/package-lock.json'

      - name: Install dependencies
        working-directory: ./rag-ui
        run: npm ci

      - name: Build the library
        working-directory: ./rag-ui
        run: npm run build

      # Add condition to only run dry-run for all triggers
      - name: Dry run npm publish
        working-directory: ./rag-ui
        run: npm publish --dry-run --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Add condition to only run actual publish for tag pushes
      # Uncomment for the real publish
      # - name: Publish to NPM
      #   if: startsWith(github.ref, 'refs/tags/v')  # Only run on version tags
      #   working-directory: ./rag-ui
      #   run: npm publish --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}