name: Python Package Release

on:
  workflow_run:
    workflows: ["Python CI"]
    types:
      - completed
    branches:
      - main

jobs:
  publish:
    name: Publish to PyPI
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main' &&
      startsWith(github.event.workflow_run.head_commit.message, 'v')
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: python/lexio/dist
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install twine
      run: python -m pip install --upgrade twine

    - name: Check Package with Twine
      working-directory: python/lexio
      run: twine check dist/*

    - name: Publish to Test PyPI
      working-directory: python/lexio
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
      run: twine upload -r testpypi dist/*

#    - name: Create Release
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      run: |
#        gh release create "${GITHUB_REF#refs/tags/}" \
#          --title "Release ${GITHUB_REF#refs/tags/}" \
#          --generate-notes \
#          dist/*